---
name: dbus-client-gen CI

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  development_environment_checks:
    strategy:
      matrix:
        include:
          - dependencies: black python3-isort
            task: make -f Makefile fmt-travis
          - dependencies: yamllint
            task: make -f Makefile yamllint
          - dependencies: pylint python3-hypothesis
            task: >
              PYTHONPATH=./src
              make -f Makefile lint
          - dependencies: python3-hypothesis
            task: >
              PYTHONPATH=./src
              make -f Makefile test
          - dependencies: python3-coverage python3-hypothesis
            task: >
              PYTHONPATH=./src
              make -f Makefile coverage
    runs-on: ubuntu-latest
    container: fedora:38  # CURRENT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: >
          dnf install -y
          make
          pip
          python
          ${{ matrix.dependencies }}
      - name: Where is userlib?
        run: >
          python -c
          'import sysconfig; print(sysconfig.get_config_var("userbase"))'
      - name: Install hs-dbus-signature
        run: pip install --user hs-dbus-signature
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}

  lowest_environment_checks:
    strategy:
      matrix:
        include:
          - dependencies: pylint python3-hypothesis python3-hs-dbus-signature
            task: PYTHONPATH=./src make -f Makefile lint
          - dependencies: python3-hypothesis python3-hs-dbus-signature
            task: PYTHONPATH=./src make -f Makefile test
          - dependencies: python3-setuptools
            task: make legacy-package
    runs-on: ubuntu-latest
    container: fedora:34  # LOWEST DEVELOPMENT ENVIRONMENT
    steps:
      - name: Display Python version
        run: python3 --version
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: >
          dnf install -y
          make
          ${{ matrix.dependencies }}
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}
