---
name: dbus-client-gen weekly

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: 20 4 * * 1
  workflow_dispatch:

jobs:
  next-fedora-python-checks:
    strategy:
      matrix:
        include:
          - dependencies: black python3-isort
            task: make -f Makefile fmt-travis
          - dependencies: yamllint
            task: make -f Makefile yamllint
          - dependencies: pylint python-hypothesis
            task: PYTHONPATH=./src make -f Makefile lint
          - dependencies: python python3-build twine
            task: make -f Makefile package
    runs-on: ubuntu-latest
    container: fedora:38  # NEXT DEVELOPMENT ENVIRONMENT
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: >
          dnf install -y
          make
          pip
          ${{ matrix.dependencies }}
      - name: Install hs-dbus-signature
        run: pip install --user hs-dbus-signature
      - name: ${{ matrix.task }}
        run: ${{ matrix.task }}
